---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: opct-e2e-webhook
  namespace: opct
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: opct-e2e-webhook-clusterrole
rules:
- apiGroups: ["admissionregistration.k8s.io"]
  resources: ["mutatingwebhookconfigurations"]
  verbs: ["create", "get", "list", "watch", "update", "patch", "delete"]
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["create", "get", "list", "watch", "update", "patch", "delete"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: opct-e2e-webhook-clusterrolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: opct-e2e-webhook-clusterrole
subjects:
- kind: ServiceAccount
  name: opct-e2e-webhook
  namespace: opct
