apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  name: opct-e2e-webhook
  namesmapce: opct
webhooks:
- name: opct-e2e-webhook.opct.svc
  clientConfig:
    service:
      name: opct-e2e-webhook
      namespace: opct
      path: "/mutate"
    caBundle: {{ .CertCA }}
  rules:
  - operations: ["CREATE"]
    apiGroups: [""]
    apiVersions: ["v1"]
    resources: ["pods"]
  admissionReviewVersions: ["v1"]
  sideEffects: None
