---
name: release-tag
on: 
  push:
    tags:
      - 'v*.*.*'

jobs:
  linters:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Shellcheck - hack
        uses: azohra/shell-linter@latest
        with:
          path: "hack/*.sh"

      - name: Shellcheck - Plugin - openshift-tests
        uses: azohra/shell-linter@latest
        with:
          path: './openshift-tests-provider-cert/plugin/*.sh'

      - name: Shellcheck - Plugin - openshift-tests - hack
        uses: azohra/shell-linter@latest
        with:
          path: './openshift-tests-provider-cert/hack/*.sh'

#
# Releasing: triggered when a tag is created
#
  release:
    if: startsWith(github.ref, 'refs/tags/')
    runs-on: ubuntu-latest
    needs: [linters]
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Set vars
        id: vars
        run: echo ::set-output name=tag::${GITHUB_REF#refs/*/}

      - name: Push Container image
        env:
          RELEASE_VERSION: ${{ steps.vars.outputs.tag }}
          QUAY_USER: ${{ secrets.QUAY_USER }}
          QUAY_PASS: ${{ secrets.QUAY_PASS }}
          EXPIRE: never
        run: |
          podman login -u="${QUAY_USER}" -p="${QUAY_PASS}" quay.io
          echo "> Build and publish container image:"
          make build-arch-amd64 VERSION=${VERSION}
          make build-arch-arm64 VERSION=${VERSION}
          make push-manifests VERSION=${VERSION}

      # https://github.com/mikepenz/release-changelog-builder-action#configuration
      - name: Build Changelog
        id: github_release
        uses: mikepenz/release-changelog-builder-action@v3.7.0
        with:
          configuration: ".github/workflows/changelog-configuration.json"

      # https://github.com/softprops/action-gh-release
      - name: Create Release on Github
        uses: softprops/action-gh-release@v0.1.15
        env:
          RELEASE_VERSION: ${{ steps.vars.outputs.tag }}
        with:
          body: |
            ## Changelog
            Image published to [quay.io/ocp-cert/openshift-tests-provider-cert:$RELEASE_VERSION](https://quay.io/repository/ocp-cert/openshift-tests-provider-cert?tab=tags)
            ${{steps.github_release.outputs.changelog}}
