---
name: release-devel
on:
  pull_request:
  push:
    branches: [main]

jobs:
  linters:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Shellcheck - hack
        uses: azohra/shell-linter@latest
        with:
          path: "hack/*.sh"

      - name: Shellcheck - Plugin - openshift-tests
        uses: azohra/shell-linter@latest
        with:
          path: './openshift-tests-provider-cert/plugin/*.sh'

      - name: Shellcheck - Plugin - openshift-tests - hack
        uses: azohra/shell-linter@latest
        with:
          path: './openshift-tests-provider-cert/hack/*.sh'

#
# Build container image
#
  build-amd64:
    name: build container amd64
    runs-on: ubuntu-latest
    needs: [linters]
    env:
      VERSION: "v0.0.0-devel-pr.${{ github.event.pull_request.number }}-amd64"
      TOOLS_REPO: localhost/tools
      PLUGIN_TESTS_REPO: localhost/plugin-openshift-tests
      MGM_REPO: localhost/must-gather-monitoring

    environment: production
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Build images AMD64
        shell: bash
        env:
          QUAY_USER: ${{ secrets.QUAY_USER }}
          QUAY_PASS: ${{ secrets.QUAY_PASS }}
          PLATFORMS: linux/amd64
        run: |
          podman login -u="${QUAY_USER}" -p="${QUAY_PASS}" quay.io
          echo "> Build and publish container image:"
          set -x
          make images VERSION="${VERSION}" PLATFORMS="${PLATFORMS}" COMMAND=push

  build-arm64:
    name: build container arm64
    runs-on: macos-13
    needs: [linters]
    env:
      VERSION: "v0.0.0-devel-pr.${{ github.event.pull_request.number }}"
      TOOLS_REPO: localhost/tools
      PLUGIN_TESTS_REPO: localhost/plugin-openshift-tests
      MGM_REPO: localhost/must-gather-monitoring

    environment: production
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Build images ARM64
        shell: bash
        env:
          PLATFORMS: linux/arm64
        run: |
          set -x
          brew tap cfergeau/crc || true
          brew reinstall vfkit || true
          brew install bzip2 || true
          brew install podman
          # https://github.com/containers/podman/issues/21842#issuecomment-2147821775
          podman machine reset || true
          podman machine init || true
          podman system connection list || true
          podman machine start || true
          set +x
          echo "> Build and publish container image:"
          make images VERSION=${VERSION} PLATFORMS="${PLATFORMS}"

#
# Releasing: triggered when a tag is created
#
  release:
    # if: startsWith(github.ref, 'refs/head/main')
    name: release container(latest)
    runs-on: macos-13
    needs:
      - build-amd64
      - build-arm64
    env:
      TOOLS_REPO: localhost/tools
      PLUGIN_TESTS_REPO: localhost/plugin-openshift-tests
      MGM_REPO: localhost/must-gather-monitoring
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Build and push container images
        shell: bash
        env:
          QUAY_USER: ${{ secrets.QUAY_USER }}
          QUAY_PASS: ${{ secrets.QUAY_PASS }}
          EXPIRE: never
          VERSION: latest
        run: |
          podman login -u="${QUAY_USER}" -p="${QUAY_PASS}" quay.io
          echo "> Build and publish container image:"
          make images VERSION=${VERSION} COMMAND=push
